version: 2.1
jobs:
  build:
    macos:
      xcode: "14.2.0"
    # resource_class: macos-m1.free
    working_directory: ~/rentachef-react-native
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yarn add @gorhom/portal
            yarn install 
            npx react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios
            cd ios && pod repo update && arch -x86_64 pod install --repo-update && cd ..
            export NODE_OPTIONS=--openssl-legacy-provider
      # Add a step to decode the provisioning profile
      - run:
          name: Decode Provisioning Profile
          command: base64 -D -i .circleci/profiles/RAC_Labs_Rentachef__AppStore.mobileprovision -o AppStore.mobileprovision
      # Add a step to decode the .p12 certificate
      - run:
          name: Decode Certificate
          command: base64 -D -i .circleci/certs/certificate.p12 -o Certificate.p12
      # Set up code signing (You should replace the placeholders with your actual values)
      - run:
          name: Set Up Code Signing
          command: |
            cd .circleci/certs
            security create-keychain -p $KEYCHAIN_PASSWORD ios-build.keychain
            security import Certificate.p12 -k ~/Library/Keychains/ios-build.keychain -P $CERTIFICATE_PASSWORD -T /usr/bin/codesign
            cd ..
            cd profiles
            security import AppStore.mobileprovision -k ~/Library/Keychains/ios-build.keychain -T /usr/bin/codesign
            security list-keychains -s ios-build.keychain
            security default-keychain -s ios-build.keychain          
      - run:
          name: Build iOS app
          command: |
            sed -i '' 's/hadOverflow() |/ hadOverflow() ||/' /Users/distiller/rentachef-react-native/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp
            cd ios
            export NODE_OPTIONS=--openssl-legacy-provider
            xcodebuild  -workspace rentachef.xcworkspace -scheme rentachef   -configuration Release   -archivePath build/rentachef.xcarchive archive CODE_SIGN_IDENTITY="iPhone Distribution" PROVISIONING_PROFILE=$PROV_PROFILE_APPLE_STORE_UUID
      - run:
          name: Create archive and IPA
          command: |
             cd ios  
             xcodebuild -workspace rentachef.xcworkspace -scheme rentachef  -configuration Release archive -archivePath $PWD/build/rentachef.xcarchive -allowProvisioningUpdates $APPLE_ID_KEY_ID	-authenticationKeyIssuerID $APPLE_ID_ISSUER_ID
             ls $PWD/build/
             xcodebuild -exportArchive -archivePath $PWD/build/rentachef.xcarchive -exportPath Release -exportOptionsPlist rentachef/Info.plist  -allowProvisioningUpdates    $APPLE_ID_KEY_ID	-authenticationKeyIssuerID $APPLE_ID_ISSUER_ID    

workflows:
  build_and_deploy:
    jobs:
      - build
