version: 2.1
jobs:
  build:
    macos:
      xcode: "12.5.1"
    working_directory: ~/rentachef-react-native
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yarn install
            cd ios && pod repo update &&  pod install --repo-update && cd ..
      - run:
          name: Build iOS app
          command: |
            cd ios
            xcodebuild  -workspace rentachef.xcworkspace -scheme rentachef   -configuration Release build PROVISIONING_PROFILE_SPECIFIER="Xcode Managed Profile"  -allowProvisioningUpdates
workflows:
  build_and_deploy:
    jobs:
      - build
