version: 2.1
jobs:
  build:
    macos:
      xcode: "14.2.0"
    # resource_class: macos-m1.free
    working_directory: ~/rentachef-react-native
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yarn add @gorhom/portal
            yarn install 
            cd ios && pod repo update &&  pod install --repo-update && cd ..
            export NODE_OPTIONS=--openssl-legacy-provider
            npx react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios
      - run:
            name: decode Certificates
            context: certificate
            command:  |
              base64 -D -o Certificates.p12 \<<<  $Certificates
              base64 -D -o App_Store.mobileprovision \<<< $App_Store_Profile

      - run:
          name: make Provisioning Profiles directory
          command: |
           mkdir -pv ~/Library/MobileDevice/Provisioning\ Profiles/
           
           sudo mkdir -pvm777 /Library/MobileDevice/Provisioning\ Profiles/
      - run:
          name: decode Provisioning Profiles
          context: certificate
          command: |
             openssl version
             cp -r App_Store.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
             
          
      - run:
          name: Build iOS app
          command: |
            sed -i '' 's/hadOverflow() |/ hadOverflow() ||/' /Users/distiller/rentachef-react-native/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp
            cd ios
            export NODE_OPTIONS=--openssl-legacy-provider
            xcodebuild  -workspace rentachef.xcworkspace -scheme rentachef   -configuration Release   -xcconfig exclue.xcconfig -quiet -allowProvisioningUpdates -authenticationKeyID $APPLE_ID_KEY_ID	-authenticationKeyIssuerID $APPLE_ID_ISSUER_ID 
            
      - run:
          name: Create archive and IPA
          command: |
             cd ios  
             xcodebuild -workspace rentachef.xcworkspace -scheme rentachef  -configuration Release archive -archivePath $PWD/build/rentachef.xcarchive -allowProvisioningUpdates $APPLE_ID_KEY_ID	-authenticationKeyIssuerID $APPLE_ID_ISSUER_ID
             ls $PWD/build/
             xcodebuild -exportArchive -archivePath $PWD/build/rentachef.xcarchive -exportPath Release -exportOptionsPlist rentachef/Info.plist  -allowProvisioningUpdates    $APPLE_ID_KEY_ID	-authenticationKeyIssuerID $APPLE_ID_ISSUER_ID    

workflows:
  build_and_deploy:
    jobs:
      - build
