version: 2.1
jobs:
  build:
    macos:
      xcode: "12.5.1"
    working_directory: ~/rentachef-react-native
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yarn install
            cd ios && pod repo update &&  pod install --repo-update && cd ..
      - run:
            name: decode Certificates
            context: certificate
            command:  echo "$Certificates" | base64 -D -o Certificates.p12 
      - run:
          name: make Provisioning Profiles directory
          command: mkdir -pv ~/Library/MobileDevice/Provisioning\ Profiles/
      - run:
          name: decode Provisioning Profiles
          context: certificate
          command: base64 -D -o ~/Library/MobileDevice/Provisioning\ Profiles/App_Store.mobileprovision <<< $App_Store_Profile
          
      - run:
          name: Build iOS app
          command: |
            cd ios
            xcodebuild  -workspace rentachef.xcworkspace -scheme rentachef   -configuration Release build PROVISIONING_PROFILE_SPECIFIER="Xcode Managed Profile" CODE_SIGN_IDENTITY="Q69U7468QY" DEVELOPMENT_TEAM="Junaid Pasha" -allowProvisioningUpdates
workflows:
  build_and_deploy:
    jobs:
      - build
