version: 2.1
jobs:
  build:
    macos:
      xcode: "15.0.0"
    working_directory: ~/rentachef-react-native
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yarn install
            cd ios && pod repo update &&  pod install --repo-update && cd ..
      - run:
            name: decode Certificates
            context: certificate
            command:  echo "$Certificates" | base64 -D -o Certificates.p12 
      - run:
          name: make Provisioning Profiles directory
          command: |
           mkdir -pv ~/Library/MobileDevice/Provisioning\ Profiles/
           
           sudo mkdir -pvm777 /Library/MobileDevice/Provisioning\ Profiles/
      - run:
          name: decode Provisioning Profiles
          context: certificate
          command: |
             base64 -D -o ~/Library/MobileDevice/Provisioning\ Profiles/App_Store.mobileprovision \<<< $App_Store_Profile
             cp -r ~/Library/MobileDevice/Provisioning\ Profiles/App_Store.mobileprovision  /Library/MobileDevice/Provisioning\ Profiles/
             
          
      - run:
          name: Build iOS app
          # command: |
          #    gem install fastlane -NV
          #    fastlane build
          command: |
            cd ios
            xcodebuild  -workspace rentachef.xcworkspace -scheme rentachef   -configuration Release -allowProvisioningUpdates PROVISIONING_PROFILE ="a305a650-05b0-4261-999f-0c561f3d812f"
workflows:
  build_and_deploy:
    jobs:
      - build
