version: 2.1
jobs:
  build:
    macos:
      xcode: "15.0.0"
    working_directory: ~/rentachef-react-native
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            rm -rf ~/Library/Developer/Xcode/DerivedData/*
            yarn install
            cd ios && pod repo update &&  pod install --repo-update && cd ..
      - run:
            name: prepare provisioning profile
            context: certificate
            command: |
               echo -n "$Certificates" | base64 -D -o certificate.p12
               echo -n "$App_Store_Profile" | base64 -D -o App_Store.mobileprovision 
               security create-keychain -p "$KEYCHAIN_PASSWORD" mykeychain.keychain
               security set-keychain-settings -lut 21600 mykeychain.keychain
               security default-keychain -s mykeychain.keychain
               security unlock-keychain -p "$KEYCHAIN_PASSWORD" mykeychain.keychain
               security import certificate.p12  -f pkcs12 -k mykeychain.keychain



             
          
      # - run:
      #     name: Build iOS app
      #     command: |
      #       cd ios
      #       rm -rf ~/Library/Developer/Xcode/DerivedData/*
      #       xcodebuild  -workspace rentachef.xcworkspace -scheme rentachef   -configuration Release -allowProvisioningUpdates CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED="NO"
      - run:
          name: Build Archive
          command: |
              cd ios        
              xcodebuild -workspace rentachef.xcworkspace -scheme rentachef   archive -archivePath $PWD/build/rentachef.xcarchive -allowProvisioningUpdates
      - run:
          name: Create IPA
          command: |
             cd ios        
             xcodebuild -exportArchive -allowProvisioningUpdates -archivePath $PWD/build/rentachef.xcarchive -exportPath Release -exportOptionsPlist exportOptions.plist


            

workflows:
  build_and_deploy:
    jobs:
      - build
