version: 2.1
jobs:
  build:
    macos:
      xcode: "12.5.1"
    working_directory: ~/rentachef-react-native
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yarn install
            cd ios && pod repo update &&  gem install cocoapods -v 1.7.5 &&  pod install && cd ..
      - run:
          name: Build iOS app
          command: |
            cd ios
            xcodebuild build-for-testing -workspace CLI.xcworkspace -scheme CLI -destination generic/platform=iOS
workflows:
  build_and_deploy:
    jobs:
      - build
