source "https://rubygems.org"

gem "fastlane"
# App scheme name
scheme("rentachef")
#provide provisioning profiles to use
export_options({
   method: "app-store",
   provisioningProfiles: {
        "com.raclabs.rentachef" => "match AppStore com.raclabs.rentachef",
        }
})
# Specify the path to store .ipa file
output_directory("./fastlane/builds")
# Excludes bitcode from the build
include_bitcode(false)
# Excludes symbols from the build.
include_symbols(false)
