-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgA9GOgUyCrxqOJZRT
J+Teja5kGhHvrg3Y5TH2/AX8fmWgCgYIKoZIzj0DAQehRANCAASuBfUYuXnhbvl2
THJc+IJt104Ng5qIEY0iA/FhmGmbQ7MC3AWmRgBqib/SPAYIZXsdG6Koi1xZVX8n
b8hsshqQ
-----END PRIVATE KEY-----