# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Release to AppStore"
  lane :release do
    match(type: "appstore")
    gym("rentachef")
    app_store_connect_api_key(
      key_id: "M9TJ4K9P8Y",
      issuer_id: "69a6de73-f7c5-47e3-e053-5b8c7c11a4d1",
      key_filepath: "./AuthKey_M9TJ4K9P8Y.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )

    # Automatically loads Actions.lane_context[SharedValues::APP_STORE_CONNECT_API_KEY]
    pilot
  end

  lane :release_rentachef_to_testflight do
    # Build your app
    release
  end
end




