# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Install Profiles and Build My App"
  lane :release do
    app_store_connect_api_key(
      key_id: "M9TJ4K9P8Y",
      issuer_id: "69a6de73-f7c5-47e3-e053-5b8c7c11a4d1",
      key_filepath: "./AuthKey_M9TJ4K9P8Y.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )

    # Automatically loads Actions.lane_context[SharedValues::APP_STORE_CONNECT_API_KEY]
    pilot
  end

  lane :build_ipa do
    install_provisioning_profile(path: "/Users/distiller/rentachef-react-native/.circleci/profiles/RAC_Labs_Rentachef.mobileprovision") # This will install provision profiles at run time if needed when you run the fastlane lane
    import_certificate(
      certificate_path: "/Users/distiller/rentachef-react-native/.circleci/certs/certificate.p12",
      certificate_password: "rac2023"
    )
    gym(
      workspace: "rentachef.xcworkspace",
      scheme: "rentachef",
      output_directory: "/Users/distiller/rentachef-react-native",
      output_name: "renta.ipa",
      clean: true
    )
  end

  lane :release_rentachef_to_testflight do
    # Build your app
    build_ipa
  end
end




