# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc “Sync signing”
   lane :signing do
   
   sync_code_signing 
   mapping = Actions.lane_context[
   SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING
   ]
   update_code_signing_settings()
   end

  desc "Install Profiles and Build My App"
  lane :build_ipa do
    install_provisioning_profile(path: "/Users/distiller/rentachef-react-native/.circleci/profiles/RAC_Labs_Rentachef__AppStore.mobileprovision") 
    gym(
      workspace: "rentachef.xcworkspace",
      scheme: "rentachef",
      output_directory: "./ios",
      output_name: "rentachef.ipa",
      include_bitcode: false,
      clean: true,
      export_options: {
         method: "app-store",
         provisioningProfiles: {
           "com.raclabs.rentachef" => "match AppStore com.raclabs.rentachef",
              }
      }
    )
    end

  lane :release_rentachef_to_testflight do
    # Build your app
    signing
    build_ipa
  end
end




